# This is a basic workflow to help you get started with Actions

name: create-binaries

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create-linux-binary
        run: |
          pip install --upgrade pip
          pip install palworld_coord msgpack pyperclip
          cd /tmp
          git clone https://github.com/magicbear/palworld-server-toolkit.git palworld-server-toolkit-auto-update
          cd palworld-server-toolkit-auto-update
          git clone https://github.com/cheahjs/palworld-save-tools.git palworld_save_tools
          git clone https://github.com/cheahjs/palworld-save-tools.git save_tools
          git clone https://github.com/magicbear/PalEdit.git pal_edit
          git clone https://github.com/magicbear/PalEdit.git palworld_pal_edit
          cp -rf palworld_save_tools/palworld_save_tools/* palworld_save_tools/
          cp -rf save_tools/palworld_save_tools/* save_tools/
          cp -rf pal_edit/palworld_pal_edit/* pal_edit/
          cp -rf palworld_pal_edit/palworld_pal_edit/* palworld_pal_edit/
          pip install -r requirements.txt
          cd pal_edit
          pip install -r requirements.txt
          cd ../palworld_pal_edit
          pip install -r requirements.txt
          cd ../palworld_server_toolkit
          pyinstaller --noconfirm --onefile --windowed --hidden-import=PIL "editor.py"
          cd dist
          mkdir palworld-server-toolkit-auto-update-linux-binary
          ls
          mv editor palworld-server-toolkit-auto-update-linux-binary/
          mkdir palworld-server-toolkit-auto-update-linux-binary/resources
          cp -rf ../../palworld_pal_edit/resources/* palworld-server-toolkit-auto-update-linux-binary/resources/
          cp -rf ../resources/* palworld-server-toolkit-auto-update-linux-binary/resources/
          zip -r /tmp/palworld-server-toolkit-auto-update-linux-binary.zip /tmp/palworld-server-toolkit-auto-update/palworld_server_toolkit/dist/palworld-server-toolkit-auto-update-linux-binary
          ls /tmp
          echo "--> BUILDING \"linux-binary\" DONE! <--"
      - name: uploding linux-binary artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          name: palworld-server-toolkit-auto-update-linux-binary.zip
          path: /tmp/palworld-server-toolkit-auto-update-linux-binary.zip
  
  build-macos-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: create-macos-binary
        run: |
          pip install --upgrade pip
          pip install palworld_coord msgpack pyperclip
          cd /tmp
          git clone https://github.com/magicbear/palworld-server-toolkit.git palworld-server-toolkit-auto-update
          cd palworld-server-toolkit-auto-update
          git clone https://github.com/cheahjs/palworld-save-tools.git palworld_save_tools
          git clone https://github.com/cheahjs/palworld-save-tools.git save_tools
          git clone https://github.com/magicbear/PalEdit.git pal_edit
          git clone https://github.com/magicbear/PalEdit.git palworld_pal_edit
          cp -rf palworld_save_tools/palworld_save_tools/* palworld_save_tools/
          cp -rf save_tools/palworld_save_tools/* save_tools/
          cp -rf pal_edit/palworld_pal_edit/* pal_edit/
          cp -rf palworld_pal_edit/palworld_pal_edit/* palworld_pal_edit/
          pip install -r requirements.txt
          cd pal_edit
          pip install -r requirements.txt
          cd ../palworld_pal_edit
          pip install -r requirements.txt
          cd ../palworld_server_toolkit
          pyinstaller --noconfirm --onefile --windowed --hidden-import=PIL "editor.py"
          cd dist
          mkdir palworld-server-toolkit-auto-update-macos-binary
          mv editor palworld-server-toolkit-auto-update-macos-binary/
          mv editor.app palworld-server-toolkit-auto-update-macos-binary/
          mkdir palworld-server-toolkit-auto-update-macos-binary/resources
          cp -rf ../../palworld_pal_edit/resources/* palworld-server-toolkit-auto-update-macos-binary/resources/
          cp -rf ../resources/* palworld-server-toolkit-auto-update-macos-binary/resources/
          zip -r /tmp/palworld-server-toolkit-auto-update-macos-binary.zip /tmp/palworld-server-toolkit-auto-update/palworld_server_toolkit/dist/palworld-server-toolkit-auto-update-macos-binary
          ls /tmp
          echo "--> BUILDING \"macos-binary\" DONE! <--"
      - name: uploding macos-binary artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          name: palworld-server-toolkit-auto-update-macos-binary.zip
          path: /tmp/palworld-server-toolkit-auto-update-macos-binary.zip

  build-windows-binary:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: create-windows-binary
        run: |
          pip install --upgrade pip
          pip install palworld_coord msgpack pyperclip
          cd /
          mkdir tmp
          cd \tmp
          git clone https://github.com/magicbear/palworld-server-toolkit.git palworld-server-toolkit-auto-update
          cd palworld-server-toolkit-auto-update
          git clone https://github.com/cheahjs/palworld-save-tools.git palworld_save_tools
          git clone https://github.com/cheahjs/palworld-save-tools.git save_tools
          git clone https://github.com/magicbear/PalEdit.git pal_edit
          git clone https://github.com/magicbear/PalEdit.git palworld_pal_edit
          xcopy .\palworld_save_tools\palworld_save_tools\* .\palworld_save_tools\ /E/H/Y
          xcopy .\save_tools\palworld_save_tools\* .\save_tools\ /E/H/Y
          xcopy .\pal_edit\palworld_pal_edit\* .\pal_edit\ /E/H/Y
          xcopy .\palworld_pal_edit\palworld_pal_edit\* .\palworld_pal_edit\ /E/H/Y
          pip install -r requirements.txt
          cd pal_edit
          pip install -r requirements.txt
          cd ..\palworld_pal_edit
          pip install -r requirements.txt
          cd ..\palworld_server_toolkit
          pyinstaller --noconfirm --onefile --windowed --hidden-import=PIL "editor.py"
          cd dist
          mkdir palworld-server-toolkit-auto-update-windows-binary
          move editor.exe palworld-server-toolkit-auto-update-windows-binary\
          mkdir palworld-server-toolkit-auto-update-windows-binary\resources
          xcopy ..\..\palworld_pal_edit\resources\* palworld-server-toolkit-auto-update-windows-binary\resources\ /E/H/Y
          xcopy ..\resources\* palworld-server-toolkit-auto-update-windows-binary\resources\ /E/H/Y
          powershell Compress-Archive \tmp\palworld-server-toolkit-auto-update\palworld_server_toolkit\dist\palworld-server-toolkit-auto-update-windows-binary \tmp\palworld-server-toolkit-auto-update-windows-binary.zip
          dir \tmp
          echo '--> BUILDING "windows-binary" DONE! <--'
      - name: uploding windows-binary artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          name: palworld-server-toolkit-auto-update-windows-binary.zip
          path: /tmp/palworld-server-toolkit-auto-update-windows-binary.zip

  build-python-plain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create-python-plain
        run: |
          cd /tmp
          git clone https://github.com/magicbear/palworld-server-toolkit.git --recurse-submodules palworld-server-toolkit-auto-update
          cd palworld-server-toolkit-auto-update
          git clone https://github.com/EternalWraith/PalEdit pal_edit
          git submodule update --remote
          cd /tmp
          zip -r palworld-server-toolkit-auto-update-python-plain.zip palworld-server-toolkit-auto-update
          ls /tmp
          echo "--> BUILDING \"python-plain\" DONE! <--"
      - name: uploding python-plain artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          name: palworld-server-toolkit-auto-update-python-plain.zip
          path: /tmp/palworld-server-toolkit-auto-update-python-plain.zip
