# This is a basic workflow to help you get started with Actions

name: create-macos-binary

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: create-macos-binary
        run: |
          pip install --upgrade pip
          pip install palworld_coord msgpack pyperclip
          cd /tmp
          git clone https://github.com/magicbear/palworld-server-toolkit.git palworld-server-toolkit-auto-update
          cd palworld-server-toolkit-auto-update
          git clone https://github.com/cheahjs/palworld-save-tools.git palworld_save_tools
          git clone https://github.com/cheahjs/palworld-save-tools.git save_tools
          git clone https://github.com/magicbear/PalEdit.git pal_edit
          git clone https://github.com/magicbear/PalEdit.git palworld_pal_edit
          cp -rf palworld_save_tools/palworld_save_tools/* palworld_save_tools/
          cp -rf save_tools/palworld_save_tools/* save_tools/
          cp -rf pal_edit/palworld_pal_edit/* pal_edit/
          cp -rf palworld_pal_edit/palworld_pal_edit/* palworld_pal_edit/
          pip install -r requirements.txt
          cd pal_edit
          pip install -r requirements.txt
          cd ../palworld_pal_edit
          pip install -r requirements.txt
          cd ../palworld_server_toolkit
          pyinstaller --noconfirm --onefile --windowed --hidden-import=PIL "editor.py"
          cd dist
          mkdir palworld-server-toolkit-auto-update-macos-binary
          mv editor palworld-server-toolkit-auto-update-macos-binary/
          mv editor.app palworld-server-toolkit-auto-update-macos-binary/
          mkdir palworld-server-toolkit-auto-update-macos-binary/resources
          cp -rf ../../palworld_pal_edit/resources/* palworld-server-toolkit-auto-update-macos-binary/resources/
          cp -rf ../resources/* palworld-server-toolkit-auto-update-macos-binary/resources/
          zip -r /tmp/palworld-server-toolkit-auto-update-macos-binary.zip /tmp/palworld-server-toolkit-auto-update/palworld_server_toolkit/dist/palworld-server-toolkit-auto-update-macos-binary
          ls /tmp
          echo "--> BUILDING DONE! <--"
